# Generated by Django 5.1.6 on 2026-06-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(help_text='Please upload a passport size photo of yourself', upload_to='profile_pics/', verbose_name='Profile Picture (User Pic)')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('education', models.CharField(choices=[('high_school', 'High School / Intermediate'), ('undergraduate', 'Undergraduate Student'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate'), ('other', 'Other')], max_length=20, verbose_name='Educational Qualification')),
                ('course', models.CharField(choices=[('fullstack', 'Full Stack Web Development'), ('python_django', 'Python & Django Backend'), ('ds_ml', 'Data Science & Machine Learning'), ('ui_ux', 'UI/UX Design'), ('cybersecurity', 'Cybersecurity')], max_length=20, verbose_name='Chosen Course')),
                ('batch', models.CharField(choices=[('morning', 'Morning Batch (8:00 AM - 10:00 AM)'), ('afternoon', 'Afternoon Batch (2:00 PM - 4:00 PM)'), ('evening', 'Evening Batch (6:00 PM - 8:00 PM)'), ('weekend', 'Weekend Batch (Sat & Sun, 10:00 AM - 1:00 PM)')], max_length=20, verbose_name='Preferred Batch')),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (No prior coding experience)'), ('intermediate', 'Intermediate (Some coding knowledge)'), ('advanced', 'Advanced (Proficient / Professional)')], max_length=20, verbose_name='Programming Experience')),
                ('comments', models.TextField(blank=True, help_text='Tell us what you hope to achieve in this course', verbose_name='Additional Comments / Learning Goals')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'verbose_name': 'Student Registration',
                'verbose_name_plural': 'Student Registrations',
                'ordering': ['-registered_at'],
            },
        ),
    ]
