# Generated by Django 5.1.6 on 2026-06-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='Upload the screenshot of the QR code payment', null=True, upload_to='payment_screenshots/', verbose_name='Payment Screenshot'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid (Pending Verification)'), ('verified', 'Payment Verified')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Date'),
        ),
    ]
